Fix mypy 'safe-super' error.
Mypy now complains about the useless constructor in the
`ControllerDependencyInjector` abstract base class:

  full_offline_backup_for_todoist/runtime.py:15: error: Call to
  abstract method "__init__" of "ControllerDependencyInjector" with
  trivial body via super() is unsafe  [safe-super]

Since the call to the constructor of `ControllerDependencyInjector`
is indeed useless (the constructor is empty), just remove it.